// Generated by https://quicktype.io

export interface ID1AuthorJoshConstineImageHTTPSPBSTwimgCOMMediaD1KNUQ8VAAAEx8LJpgMessageTHREADAfterWritingHundredsOfArticlesAboutAboutAppsThisYearHereSMyWishlistOfFeatureLaunchesLikeTwitterDMSearchUberQuietRideFirstUpInstagram1LikesNickSteve2CommentsAuthorSteve2MessageThanksAuthorJoshConstineMessageNoProblem {
    id:       number;
    author:   string;
    image:    string;
    message:  string;
    kudos:    string[];
    comments: Comment[];
}

export interface Comment {
    author:  string;
    message: string;
}
