// Generated by https://quicktype.io

import { User } from "./user";

export interface Flit {
    id:       number;
    author:   string;
    image:    string;
    message:  string;
    date: Date;
    kudos:    User[]; //list of users that gave a kudo to this flit
    comments: Comment[];
}

export interface Comment {
    author:  string;
    message: string;
    kudos: User[];
}
