// Generated by https://quicktype.io

import { User } from './user'

export interface Flit {
    _id: string;
    author: string;
    image: string;
    message: string;
    date: Date;
    kudos: string[]; //list of users that gave a kudo to this flit
    comments: Comment[];
}

export interface Comment {
    author: string;
    message: string;
    date: Date;
    kudos: string[];
}
